import csv

questions_and_answers = [
    {"question": "What is the largest mammal?", "answer": "Blue Whale"},
    {"question": "Who is the CEO of SpaceX?", "answer": "Elon Musk"},
    {"question": "What is the largest planet in our solar system?", "answer": "Jupiter"},
    {"question": "What is the smallest prime number?", "answer": "2"},
    {"question": "What is the boiling point of water at sea level in Celsius?", "answer": "100 degrees"},
    {"question": "What is the capital of Japan?", "answer": "Tokyo"},
    {"question": "What is the chemical symbol for gold?", "answer": "Au"},
    {"question": "What is the longest river in the world?", "answer": "Nile"},
    {"question": "Who is known as the father of modern physics?", "answer": "Albert Einstein"},
    {"question": "What is the smallest country in the world?", "answer": "Vatican  City"},
    {"question": "What is the capital of Canada?", "answer": "Ottawa"},
    {"question": "What is the tallest mountain in the world?", "answer": "Mount Everest"},
    {"question": "What is the powerhouse of the cell?", "answer": "Mitochondria"},
    {"question": "What is the capital of Italy?", "answer": "Rome"},
    {"question": "What is the hardest natural material?", "answer": "Diamond"},
    {"question": "What is the largest desert in the world?", "answer": "Sahara"},
    {"question": "What is the chemical symbol for silver?", "answer": "Ag"},
    {"question": "What is the chemical formula for table salt?", "answer": "NaCl"},
    {"question": "What is the largest ocean on Earth?", "answer": "Pacific Ocean"},
    {"question": "What is the capital of Russia?", "answer": "Moscow"},
    {"question": "What is the smallest country in the world?", "answer": "Vatican City"},
    {"question": "What is the largest planet in our solar system?", "answer": "Jupiter"},
    {"question": "What is the process by which plants make their own food?", "answer": "Photosynthesis"},
    {"question": "What is the largest living species of lizard?", "answer": "Komodo dragon"},
    {"question": "What is the deepest part of the ocean?", "answer": "Challenger Deep"},
    {"question": "What is the highest mountain peak in the solar system?", "answer": "Olympus Mons"},
    {"question": "What is the largest mammal on Earth?", "answer": "Blue whale"},
    {"question": "What is the process by which the Earth's plates move?", "answer": "Plate tectonics"},
    {"question": "What is the largest type of shark?", "answer": "Whale shark"},
    {"question": "What is the highest waterfall in the world?", "answer": "Angel Falls"},
    {"question": "What is the largest species of turtle?", "answer": "Leatherback sea turtle"},
    {"question": "What is the process by which the Earth's rocks are formed?", "answer": "Rock cycle"},
    {"question": "What is the largest type of bear?", "answer": "Polar bear"},
    {"question": "What is the highest mountain peak in Asia?", "answer": "Mount Everest"},
    {"question": "What is the largest species of fish?", "answer": "Whale shark"},
    {"question": "What is the process by which the Earth's weather patterns are formed?", "answer": "Atmospheric circulation"},
    {"question": "What is the largest type of cat?", "answer": "Siberian tiger"},
    {"question": "What is the highest mountain peak in Europe?", "answer": "Mount Elbrus"},
    {"question": "What is the largest species of bird?", "answer": "Ostrich"},
    {"question": "What is the process by which the Earth's climate is regulated?", "answer": "Climate regulation"},
    {"question": "What is the largest type of insect?", "answer": "Goliath beetle"},
    {"question": "What is the highest mountain peak in Australia?", "answer": "Mount Kosciuszko"},
    {"question": "What is the largest species of spider?", "answer": "Goliath birdeater"},
    {"question": "What is the process by which the Earth's magnetic field is generated?", "answer": "Dynamo effect"},
    {"question": "What is the capital of Australia?", "answer": "Canberra"},
    {"question": "What is the capital of Brazil?", "answer": "Brasilia"},
    {"question": "What is the capital of China?", "answer": "Beijing"},
    {"question": "What is the capital of Germany?", "answer": "Berlin"},
    {"question": "What is the capital of India?", "answer": "New Delhi"},
    {"question": "What is the capital of Japan?", "answer": "Tokyo"},
    {"question": "What is the capital of Mexico?", "answer": "Mexico City"},
    {"question": "What is the capital of Spain?", "answer": "Madrid"},
    {"question": "What is the capital of the United Kingdom?", "answer": "London"},
    {"question": "What is the capital of the United States?", "answer": "Washington, D.C."},
    {"question": "What is the capital of Argentina?", "answer": "Buenos Aires"},
    {"question": "What is the capital of Canada?", "answer": "Ottawa"},
    {"question": "What is the capital of Egypt?", "answer": "Cairo"},
    {"question": "What is the capital of South Korea?", "answer": "Seoul"},
    {"question": "What is the capital of Vietnam?", "answer": "Hanoi"},
    {"question": "What is the capital of Thailand?", "answer": "Bangkok"},
    {"question": "Who is the author of the famous novel 'To Kill a Mockingbird'?", "answer": "Harper Lee"},
    {"question": "What is the chemical symbol for gold?", "answer": "Au"},
    {"question": "Which planet in our solar system is known for being the hottest?", "answer": "Venus"},
    {"question": "Who is the founder of the social media platform Facebook?", "answer": "Mark Zuckerberg"},
    {"question": "What is the largest living species of bird?", "answer": "Ostrich"},
    {"question": "Who is the lead singer of the rock band Queen?", "answer": "Freddie Mercury"},
    {"question": "What is the smallest bone in the human body?", "answer": "Stapes"},
    {"question": "Who is the author of the famous book '1984'?", "answer": "George Orwell"},
    {"question": "What is the largest species of shark?", "answer": "Whale shark"},
    {"question": "Who is the founder of the technology company Apple?", "answer": "Steve Jobs"},
    {"question": "What is the capital of Indonesia?", "answer": "Jakarta"},
    {"question": "What is the capital of Malaysia?", "answer": "Kuala Lumpur"},
    {"question": "What is the capital of Philippines?", "answer": "Manila"},
    {"question": "What is the capital of Singapore?", "answer": "Singapore"},
    {"question": "What is the capital of Taiwan?", "answer": "Taipei"},
    {"question": "What is the capital of Hong Kong?", "answer": "City of Victoria"},
    {"question": "What is the capital of Macau?", "answer": "Macau"},
    {"question": "What is the capital of Cambodia?", "answer": "Phnom Penh"},
    {"question": "What is the capital of Laos?", "answer": "Vientiane"},
    {"question": "What is the capital of Myanmar?", "answer": "Naypyidaw"},
    {"question": "What is the highest mountain peak in South America?", "answer": "Aconcagua"},
    {"question": "Who is the lead singer of the rock band Guns N' Roses?", "answer": "Axl Rose"},
    {"question": "What is the chemical symbol for copper?", "answer": "Cu"},
    {"question": "Who is the author of the famous novel 'Pride and Prejudice'?", "answer": "Jane Austen"},
    {"question": "What is the largest species of lizard?", "answer": "Komodo dragon"},
    {"question": "Who is the founder of the online retailer Amazon?", "answer": "Jeff Bezos"},
    {"question": "What is the highest mountain peak in North America?", "answer": "Denali"},
    {"question": "Who is the lead singer of the rock band AC/DC?", "answer": "Brian Johnson"},
    {"question": "What is the chemical symbol for silver?", "answer": "Ag"},
    {"question": "Who is the author of the famous novel 'The Lord of the Rings'?", "answer": "J.R.R. Tolkien"},
    {"question": "Who is the founder of the social media platform Twitter?", "answer": "Jack Dorsey"},
    {"question": "What is the chemical symbol for iron?", "answer": "Fe"},
    {"question": "Who is the founder of the technology company Microsoft?", "answer": "Bill Gates"},
    {"question": "What is the chemical symbol for zinc?", "answer": "Zn"},
    {"question": "What is the largest species of snake?", "answer": "Green anaconda"},
    {"question": "Who is the lead singer of the rock band Aerosmith?", "answer": "Steven Tyler"},
    {"question": "What is the chemical symbol for tin?", "answer": "Sn"},
    {"question": "Who is the author of the famous novel 'Moby-Dick'?", "answer": "Herman Melville"},
    {"question": "What is the largest species of spider?", "answer": "Goliath birdeater"},
    {"question": "Who is the founder of the technology company Google?", "answer": "Larry Page and Sergey Brin"},
]

with open("questions.csv", "w", newline="", encoding="utf-8") as csvfile:
    fieldnames = ["question", "answer"]
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

    writer.writeheader()
    for q_and_a in questions_and_answers:
        writer.writerow(q_and_a)